# Generated by Django 6.0.3 on 2026-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
